import React from 'react';
import './LoginModal.css';

function EmployeeLoginModal() {
  return (
    <>
      <div class="login-page">
        <div class="form">
          <form class="login-form">
            <input type="text" placeholder="employeeid" />
            <input type="password" placeholder="password" />
            <button>login</button>
            <p class="message">New employees are generated by the administrator</p>
          </form>
        </div>
      </div>
    </>
  );
}

export default EmployeeLoginModal;
