import React from 'react';
import './LoginModal.css';

function EmployeeLoginModal() {

  const loginFunction = () => {
    localStorage.setItem("LoggedIn", true);
  }

  return (
    <>
      <div className="login-page">
        <div className="form">
          <form className="login-form">
            <input type="text" placeholder="employeeid" />
            <input type="password" placeholder="password" />
            <button onClick={loginFunction()}>login</button>
            <p className="message">New employees are generated by the administrator</p>
          </form>
        </div>
      </div>
    </>
  );
}

export default EmployeeLoginModal;
